### ISSUE TITLE
missing licence

### ISSUE THREAD

**Issue by amosbin** [msimerson/postfix-parser#19]
can I kindly ask you if it would be possible to add a licence mention ?
npm says the home page is another git repo (owned by DoubleCheck), that in its turn just a fork for this one
so this one is what's considered the original software.

can I also send a PR ? (I had to ask because there is no licence) I would like to add a minor contrib
dovecot regex to parse it. 
happy holidays !!

**Comment by msimerson** [comment]
Sure, BSD 3-clause is my preferred OSS license.

**Comment by msimerson** [comment]
License is already specified in package.json.
