### ISSUE TITLE
Add default msg to output

### ISSUE THREAD

**Issue by adrianmarcu18** [msimerson/postfix-parser#24]
Sometimes, the type doesn't match to anything, and it only returns, as example:

```json
{"date":"Jan  9 17:11:57","host":"mail","prog":"postfix/smtpd","pid":"1234"}
```

When to type matches, in this cases "postfix/smtpd", you lose the other part of the message which could be useful even if not parsed.

**Comment by msimerson** [comment]
If you'd like anything to be done with those messages, provide at least the following:

• a collection of examples (the more comprehensive, the better) of the log messages
• an indication that those log messages can be reliably parsed
• a stronger argument that the messages *are* useful.

**Comment by adrianmarcu18** [comment]
My usecase is that I am using postfix-parser to continously fetch and parse postfix log files and output them to a json file. Than I am collecting the json parsed logs via elastic-agent to Elasticsearch. My requirement is that I should save all logs for auditing purposes, but also be able to create alerts for mail statuses and others. 

And because the smtpd messages are not in the final json file, I lose a lot of auditing data and traces of connections.
I do not necessarily want the message of smtpd to be parsed, but to be part of the final json file.

A simple solution would be to add an extra argument to postfix-parser to be able to switch on/off keeping the original message for all types, no matter if they were or not parsed. Working a lot with Elasticsearch and ingest pipelines, where there is also log parsing done, there is always the option to keep the original event, just in case of a wrongfully-parsed message.

Or, another solution would be to parse it as syslog if the type doesn't match the known prog.

Of course, we can also treat the particular case of smtpd like below, but would also be useful to have something for the general case.


Here is a sample of logs:

Jan  6 08:39:06 mail postfix/smtpd[339505]: 93C8388C38: client=unknown[192.168.1.0]
Jan  6 08:39:06 mail postfix/smtpd[339505]: disconnect from unknown[192.168.1.0] ehlo=1 mail=1 rcpt=1 data=1 quit=1 
Jan  6 08:39:49 mail postfix/smtpd[339505]: connect from localhost[127.0.0.1]
Jan  6 08:39:49 mail postfix/smtpd[339505]: setting up TLS connection from localhost[127.0.0.1]
Jan  6 08:39:49 mail postfix/smtpd[339505]: localhost[127.0.0.1]: TLS cipher list "aNULL:-aNULL:HIGH:MEDIUM:+RC4:@STRENGTH"
Jan  6 08:39:49 mail postfix/smtpd[339505]: SSL_accept:before/accept initialization
Jan  6 08:39:49 mail postfix/smtpd[339505]: SSL_accept error from localhost[127.0.0.1]: lost connection
Jan  6 08:39:49 mail postfix/smtpd[339505]: lost connection after CONNECT from localhost[127.0.0.1]
Jan  6 08:39:49 mail postfix/smtpd[339505]: disconnect from localhost[127.0.0.1] commands=0/0
Jan  6 08:40:49 mail postfix/smtpd[339505]: connect from localhost[127.0.0.1]
Jan  6 08:40:49 mail postfix/smtpd[339505]: setting up TLS connection from localhost[127.0.0.1]
Jan  6 08:40:49 mail postfix/smtpd[339505]: localhost[127.0.0.1]: TLS cipher list "aNULL:-aNULL:HIGH:MEDIUM:+RC4:@STRENGTH"
Jan  6 08:40:49 mail postfix/smtpd[339505]: SSL_accept:before/accept initialization
Jan  6 08:40:49 mail postfix/smtpd[339505]: SSL_accept error from localhost[127.0.0.1]: lost connection
Jan  6 08:40:49 mail postfix/smtpd[339505]: lost connection after CONNECT from localhost[127.0.0.1]
Jan  6 08:40:49 mail postfix/smtpd[339505]: disconnect from localhost[127.0.0.1] commands=0/0
Jan  6 08:40:54 mail postfix/smtpd[339505]: connect from unknown[192.168.0.1]
Jan  6 08:40:54 mail postfix/smtpd[339505]: setting up TLS connection from unknown[192.168.0.1]
Jan  6 08:40:54 mail postfix/smtpd[339505]: unknown[192.168.0.1]: TLS cipher list "aNULL:-aNULL:HIGH:MEDIUM:+RC4:@STRENGTH"
Jan  6 08:40:54 mail postfix/smtpd[339505]: SSL_accept:before/accept initialization
Jan  6 08:40:54 mail postfix/smtpd[339505]: SSL_accept:SSLv3 read client hello A
Jan  6 08:40:54 mail postfix/smtpd[339505]: SSL_accept:SSLv3 write server hello A
Jan  6 08:40:54 mail postfix/smtpd[339505]: SSL_accept:SSLv3 write certificate A
Jan  6 08:40:54 mail postfix/smtpd[339505]: SSL_accept:SSLv3 write key exchange A
Jan  6 08:40:54 mail postfix/smtpd[339505]: SSL_accept:SSLv3 write server done A
Jan  6 08:40:54 mail postfix/smtpd[339505]: SSL_accept:SSLv3 flush data
Jan  6 08:40:54 mail postfix/smtpd[339505]: SSL_accept:SSLv3 read client certificate A
Jan  6 08:40:54 mail postfix/smtpd[339505]: SSL_accept:SSLv3 read client key exchange A
Jan  6 08:40:54 mail postfix/smtpd[339505]: SSL_accept:SSLv3 read certificate verify A
Jan  6 08:40:54 mail postfix/smtpd[339505]: SSL_accept:SSLv3 read finished A


Did a small test, and doing this works for me:
![image](https://github.com/msimerson/postfix-parser/assets/48454135/5373ed4b-269a-4fb3-96d0-c6f55d1061f4)

**Comment by msimerson** [comment]
That hack breaks some other matches. Here's an example from the test suite that's now broken:

```diff
       {
-  "msg": "3mKxs35RQsz7sXF: message-id=<3mKxs308vpz7sXd@mx14.example.net>"
+  "message-id": "3mKxs308vpz7sXd@mx14.example.net"
+  "qid": "3mKxs35RQsz7sXF"
       }
```

**Comment by msimerson** [comment]
Fixed. The issue was that the version of syslog on your system uses a slightly different format. Specifically, most versions of syslog like this: `Jan  6 08:40:54` with a fixed number of characters reserved for the date. Yours does not reserve the character when a leading zero is dropped: `Jan 6 08:40:54`. I adjusted the regex to match either pattern.

**Comment by adrianmarcu18** [comment]
Nice. Thanks for the work
